const EXTRACT_VIDEO_NON_BLACK_THUMBNAIL = 'SEND_VIDEO_NON_BLACK_THUMBNAIL';
const EXTRACT_VIDEO_THUMBNAILS = 'EXTRACT_VIDEO_THUMBNAILS';
const EXTRACT_VIDEO_METADATA = 'EXTRACT_VIDEO_METADATA';

// Store related IPC channels
const STORE_ADD_VIDEO = 'STORE_ADD_VIDEO';
const STORE_REMOVE_VIDEO = 'STORE_REMOVE_VIDEO';
const STORE_GET_VIDEO_LIST = 'STORE_GET_VIDEO_LIST';
const STORE_HAS_VIDEO = 'STORE_HAS_VIDEO';
const STORE_CLEAR = 'STORE_CLEAR';
const STORE_GET_COUNT = 'STORE_GET_COUNT';
const STORE_CHANGED = 'STORE_CHANGED';

function generateMessageChannel(channel: string, arg: string | number) {
  return `${channel}-${arg}`;
}

export {
  EXTRACT_VIDEO_NON_BLACK_THUMBNAIL,
  EXTRACT_VIDEO_THUMBNAILS,
  EXTRACT_VIDEO_METADATA,
  STORE_ADD_VIDEO,
  STORE_REMOVE_VIDEO,
  STORE_GET_VIDEO_LIST,
  STORE_HAS_VIDEO,
  STORE_CLEAR,
  STORE_GET_COUNT,
  STORE_CHANGED,
  generateMessageChannel,
};
