const EXTRACT_VIDEO_NON_BLACK_THUMBNAIL = 'SEND_VIDEO_NON_BLACK_THUMBNAIL';
const EXTRACT_VIDEO_THUMBNAILS = 'EXTRACT_VIDEO_THUMBNAILS';
const EXTRACT_VIDEO_METADATA = 'EXTRACT_VIDEO_METADATA';

// Store related IPC channels
// Video Store
const STORE_ADD_VIDEO = 'STORE_ADD_VIDEO';
const STORE_REMOVE_VIDEO = 'STORE_REMOVE_VIDEO';
const STORE_GET_VIDEO_LIST = 'STORE_GET_VIDEO_LIST';
const STORE_HAS_VIDEO = 'STORE_HAS_VIDEO';
const STORE_CLEAR = 'STORE_CLEAR';
const STORE_GET_COUNT = 'STORE_GET_COUNT';
const VIDEO_STORE_CHANGED = 'STORE_CHANGED';

// Timeline Store
const STORE_ADD_VIDEO_TO_TIMELINE = 'STORE_ADD_VIDEO_TO_TIMELINE';
const STORE_REMOVE_VIDEO_FROM_TIMELINE = 'STORE_REMOVE_VIDEO_FROM_TIMELINE';
const STORE_UPDATE_VIDEO_IN_TIMELINE = 'STORE_UPDATE_VIDEO_IN_TIMELINE';
const STORE_GET_VIDEOS_IN_TIMELINE = 'STORE_GET_VIDEOS_IN_TIMELINE';
const TIMELINE_STORE_CHANGED = 'TIMELINE_STORE_CHANGED';

function generateMessageChannel(channel: string, arg: string | number) {
  return `${channel}-${arg}`;
}

export {
  // Core Video FFMPEG related Channels
  EXTRACT_VIDEO_NON_BLACK_THUMBNAIL,
  EXTRACT_VIDEO_THUMBNAILS,
  EXTRACT_VIDEO_METADATA,

  // Video Store related channels
  STORE_ADD_VIDEO,
  STORE_REMOVE_VIDEO,
  STORE_GET_VIDEO_LIST,
  STORE_HAS_VIDEO,
  STORE_CLEAR,
  STORE_GET_COUNT,
  VIDEO_STORE_CHANGED,

  // Timeline Store
  STORE_ADD_VIDEO_TO_TIMELINE,
  STORE_REMOVE_VIDEO_FROM_TIMELINE,
  STORE_UPDATE_VIDEO_IN_TIMELINE,
  STORE_GET_VIDEOS_IN_TIMELINE,
  TIMELINE_STORE_CHANGED,

  // Utility
  generateMessageChannel,
};
